version: '2'
services:
  frontend:
    build:
      context: ..
      dockerfile: containers/frontend/Dockerfile
    volumes:
      - ../src/frontend:/frontend
      - ../build:/build
      - yarn-cache:/root/.cache/yarn
    command: |
      bash -c ' \
      yarn run build && yarn run watch \
      '
  varnish:
    build:
      context: ..
      dockerfile: containers/varnish/Dockerfile
    command: |
      bash -c '\
      varnishd -f /etc/varnish/dev.vcl -s malloc,100M -a 0.0.0.0:80 \
      && varnishlog \
      '
    ports:
      - 8000:80
  nginx:
    build:
      context: ..
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ../build:/build
  web:
    build:
      context: ..
      dockerfile: containers/web/Dockerfile
    volumes:
      - ../src/web:/web
    command: |
      bash -c '\
      ./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:80 \
      '
  worker:
    build:
      context: ..
      dockerfile: containers/worker/Dockerfile
    volumes:
      - ../src/worker:/worker
    command: |
      bash -c '\
      ./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:80 \
      '
volumes:
  yarn-cache:
    driver: local
