version: '2'
services:
  frontend:
    build:
      context: ..
      dockerfile: containers/frontend/Dockerfile
    volumes:
      - ../src/frontend:/frontend
      - ../build:/build
      # create anonymous volume as described here:
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      # explanation on how anonymous volumes are cleaned up:
      # https://docs.docker.com/engine/reference/run/#/clean-up---rm
      - /frontend/node_modules
    command: yarn run watch  # watch files for live code reload
  web:
    build:
      context: ..
      dockerfile: containers/web/Dockerfile
    volumes:
      - ../src/web:/web
    command: |
      python -c '\
      import subprocess;\
      subprocess.check_call("./manage.py migrate", shell=True);\
      subprocess.check_call("./manage.py runserver 0.0.0.0:8000", shell=True);\
      '
    ports:
     - "8000:8000"
  worker:
    build:
      context: ..
      dockerfile: containers/worker/Dockerfile
    volumes:
      - ../src/worker:/worker
    command: |
      python -c '\
      import subprocess;\
      subprocess.check_call("./manage.py migrate", shell=True);\
      subprocess.check_call("./manage.py runserver 0.0.0.0:8000", shell=True);\
      '
    ports:
      - "9000:8000"
