version: '2'
services:
  varnish:
    build:
      context: ..
      dockerfile: containers/varnish/Dockerfile
    command: |
      bash -c '\
      varnishd -f /etc/varnish/dev.vcl -s malloc,100M -a 0.0.0.0:80 \
      && varnishlog \
      '
    ports:
      - 8000:80
  nginx:
    build:
      context: ..
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ../build:/build
  frontend:
    build:
      context: ..
      dockerfile: containers/frontend/Dockerfile
    volumes:
      - ../src/frontend:/frontend
      - ../build:/build
      # create anonymous volume as described here:
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      # explanation on how anonymous volumes are cleaned up:
      # https://docs.docker.com/engine/reference/run/#/clean-up---rm
      - /frontend/node_modules
    command: yarn run build && yarn run watch
  web:
    build:
      context: ..
      dockerfile: containers/web/Dockerfile
    volumes:
      - ../src/web:/web
    command: |
      bash -c '\
      ./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:80 \
      '
  worker:
    build:
      context: ..
      dockerfile: containers/worker/Dockerfile
    volumes:
      - ../src/worker:/worker
    command: |
      bash -c '\
      ./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:80 \
      '
