version: '2'
services:
  web:
    build:
      context: ..
      dockerfile: containers/web/Dockerfile
    volumes:
      - "../src/web:/web"
    command: |
      python -c '\
      import subprocess;\
      subprocess.check_call("./manage.py migrate", shell=True);\
      subprocess.check_call("./manage.py runserver 0.0.0.0:8000", shell=True);\
      '
    ports:
     - "8000:8000"
  worker:
    build:
      context: ..
      dockerfile: containers/worker/Dockerfile
    volumes:
      - "../src/worker:/worker"
    command: |
      python -c '\
      import subprocess;\
      subprocess.check_call("./manage.py migrate", shell=True);\
      subprocess.check_call("./manage.py runserver 0.0.0.0:8000", shell=True);\
      '
    ports:
      - "9000:8000"
