version: '2'
services:
  varnish:
    build:
      context: ..
      dockerfile: containers/varnish/Dockerfile
    command: |
      bash -c '\
      varnishd -f /etc/varnish/production.vcl -s malloc,100M -a 0.0.0.0:80 \
      && varnishlog \
      '
    ports:
      - 8000:80
  nginx:
    build:
      context: ..
      dockerfile: containers/nginx/Dockerfile
  web1:
    build:
      context: ..
      dockerfile: containers/web/Dockerfile
    command: |
      bash -c '\
      ./manage.py migrate --noinput --settings=web.settings.production && ./manage.py runserver 0.0.0.0:80 --settings=web.settings.production \
      '
  web2:
    build:
      context: ..
      dockerfile: containers/web/Dockerfile
    command: |
      bash -c '\
      ./manage.py runserver 0.0.0.0:80 --settings=web.settings.production \
      '
  web3:
    build:
      context: ..
      dockerfile: containers/web/Dockerfile
    command: |
      bash -c '\
      ./manage.py runserver 0.0.0.0:80 --settings=web.settings.production\
      '
  worker:
    build:
      context: ..
      dockerfile: containers/worker/Dockerfile
    command: |
      bash -c '\
      ./manage.py migrate && ./manage.py runserver 0.0.0.0:80 \
      '
  memcached1:
    build:
      context: ..
      dockerfile: containers/memcached/Dockerfile
    ports:
      - 11211:11211
  memcached2:
    build:
      context: ..
      dockerfile: containers/memcached/Dockerfile
    ports:
      - 11212:11211
