version: '2'
services:
  web:
    build:
      context: ..
      dockerfile: docker/web.docker
    volumes:
      - "../src/planit_web:/planit_web"
    command: "python -c 'import os; os.system(\"./manage.py migrate\"); os.system(\"./manage.py runserver 0.0.0.0:8000\");'"
    ports:
     - "8000:8000"
  worker:
    build:
      context: ..
      dockerfile: docker/worker.docker
    volumes:
      - "../src/planit_worker:/planit_worker"
    command: "python -c 'import os; os.system(\"./manage.py migrate\"); os.system(\"./manage.py runserver 0.0.0.0:8000\");'"
    ports:
      - "9000:8000"
