# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanIt', '0002_auto_20170118_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='position_in_list',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
